### ISSUE TITLE
Contribute default assumptions for new Iron-Air battery technology

### ISSUE THREAD

**Issue by daniel-rdt** [open-energy-transition/form-energy-storage-2#5]
For contribution of the new Iron-Air technology to upstream PyPSA-Eur, PR for assumptions need to be created to PyPSA https://github.com/PyPSA/technology-data repo either with data from Form or with substitute source if data is not referencable.

**Comment by tgilon** [comment]
I think this can be closed given our recent discussions @daniel-rdt

**Comment by tgilon** [comment]
Addressed by https://github.com/PyPSA/technology-data/pull/149
